apiVersion: v1
kind: Service
metadata:
  name: openresty-srv
  namespace: volumes-sample
  labels:
    app: openresty-srv
spec:
  type: ClusterIP
  selector:
    app: openresty-srv
  ports:
  - protocol: TCP
    port: 80
    targetPort: http

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-application-access
  namespace: volumes-sample
  labels:
    app: openresty-srv
  annotations:
    kubernetes.io/ingress.class: "nginx-host"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: prometheus.kryukov.local
    http:
      paths:
      - path: /volumes(/|$)(.*)
        backend:
          serviceName: openresty-srv
          servicePort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openresty
  namespace: volumes-sample
  labels:
    app: openresty-srv
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: openresty-srv
  template:
    metadata:
      labels:
        app: openresty-srv
    spec:
      containers:
      - name: openresty
        image: openresty/openresty
        env:
        - name: NGINX_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 120
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 120
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - name: empty-volume
            mountPath: /empty
      volumes:
        - name: empty-volume
          emptyDir: {}
