---
apiVersion: v1
kind: Service
metadata:
  name: openresty-srv-sts
  namespace: volumes-sample
  labels:
    app: openresty-srv-sts
spec:
  clusterIP: none
  selector:
    app: openresty-sts
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-application-access-sts
  namespace: volumes-sample
  labels:
    app: openresty-srv
  annotations:
    kubernetes.io/ingress.class: "nginx-host"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: prometheus.kryukov.local
      http:
        paths:
          - backend:
              serviceName: openresty-srv-sts
              servicePort: 80
            path: /volumes-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openresty-sts
  namespace: volumes-sample
  labels:
    app: openresty-sts
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: openresty-sts
  serviceName: openresty-srv-sts
  template:
    metadata:
      labels:
        app: openresty-sts
    spec:
      containers:
      - name: openresty-sts
        image: openresty/openresty
        env:
        - name: NGINX_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - name: empty-volume
            mountPath: /empty
      volumes:
        - name: empty-volume
          emptyDir: {}
